name: Data Checker

on:
  # Allows manual triggering of the workflow
  workflow_dispatch: 
  # Triggers the workflow on push to specific paths
  push:
    branches:
        - main
    paths:
      - 'data-hub/**'
      - 'integrated_data/'
  # Triggers on pull request affecting specific paths
  pull_request:
    branches:
        - main
    paths:
      - 'data-hub/**'

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run Linter on Shell Scripts
        run: shellcheck integrated_data/.sh

  monitor_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Monitor Folders for Changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            data:
              - 'data-hub/**'
              - 'db/**'

      - name: Print Changed Folders
        run: |
          echo "Data folder changed: ${{ steps.changes.outputs.data }}"git 

  data_integration:
    runs-on: ubuntu-latest
    needs: monitor_changes
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Make Script Executable
        run: chmod +x integrated_data.sh

      - name: Run Data Integration Script
        run: ./integrated_data.sh

      - name: Check the Updated Dataset
        run: wc -l db/combined_data.csv

      - name: Commit and Push Changes
        run: |
          git config --global user.name "OLUWAKEMI-AKINSIKU"
          git config --global user.email "akinsikukemisola@gmail.com"
          git add db/combined_data.csv
          git commit -m "Automated Integration Script"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run:  git push main
